server:
  port: 8080
spring:
  application:
    name: CompetitionManager
  datasource:
    druid:
      driver-class-name: dm.jdbc.driver.DmDriver
      url: jdbc:dm://localhost:5236?SCHEMA=SYSDBA&LOGINMODE=4
      username: SYSDBA
      password: SYSDBA
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID